// smoke v1.0.0 6dc82371b24d044c3b3e2bd4cf5d92af46788fff
// --
// Code generated by webrpc-gen@v0.37.2 with .. generator. DO NOT EDIT.
//
// webrpc-gen -schema=smoke/example.ridl -target=.. -emit=impl -header=example.gen.h -out=smoke/example.gen.c

#include "example.gen.h"

#include <curl/curl.h>
#include <cjson/cJSON.h>
#include <limits.h>
#include <math.h>
#include <stdio.h>

typedef struct {
    char *data;
    size_t len;
    size_t cap;
} smoke_buffer;

#if defined(__GNUC__) || defined(__clang__)
#define SMOKE_JSON_UNUSED __attribute__((unused))
#else
#define SMOKE_JSON_UNUSED
#endif

static SMOKE_JSON_UNUSED cJSON *smoke_cjson_parse(const char *text) {
    return cJSON_ParseWithOpts(text ? text : "", NULL, 1);
}

static SMOKE_JSON_UNUSED char *smoke_cjson_print_dup(const cJSON *value) {
    char *printed;
    char *copy;

    if (!value) {
        return smoke_strdup("null");
    }

    printed = cJSON_PrintUnformatted(value);
    if (!printed) {
        return NULL;
    }

    copy = smoke_strdup(printed);
    cJSON_free(printed);
    return copy;
}

static SMOKE_JSON_UNUSED int smoke_cjson_get_int64_exact(
    const cJSON *value,
    int64_t *out
) {
    double parsed;
    double integral;

    if (!out || !cJSON_IsNumber(value)) {
        return 0;
    }

    parsed = cJSON_GetNumberValue(value);
    if (!isfinite(parsed)) {
        return 0;
    }
    if (parsed < (double)INT64_MIN || parsed > (double)INT64_MAX) {
        return 0;
    }
    if (modf(parsed, &integral) != 0.0) {
        return 0;
    }

    *out = (int64_t)integral;
    return 1;
}

static SMOKE_JSON_UNUSED int smoke_cjson_get_uint64_exact(
    const cJSON *value,
    uint64_t *out
) {
    double parsed;
    double integral;

    if (!out || !cJSON_IsNumber(value)) {
        return 0;
    }

    parsed = cJSON_GetNumberValue(value);
    if (!isfinite(parsed)) {
        return 0;
    }
    if (parsed < 0.0 || parsed > (double)UINT64_MAX) {
        return 0;
    }
    if (modf(parsed, &integral) != 0.0) {
        return 0;
    }

    *out = (uint64_t)integral;
    return 1;
}

static SMOKE_JSON_UNUSED int smoke_cjson_get_double(
    const cJSON *value,
    double *out
) {
    double parsed;

    if (!out || !cJSON_IsNumber(value)) {
        return 0;
    }

    parsed = cJSON_GetNumberValue(value);
    if (!isfinite(parsed)) {
        return 0;
    }

    *out = parsed;
    return 1;
}
static void smoke_set_error(
    smoke_error *error,
    int code,
    int http_status,
    const char *name,
    const char *message,
    const char *cause
) {
    if (!error) return;
    smoke_error_free(error);
    error->code = code;
    error->http_status = http_status;
    error->name = smoke_strdup(name ? name : "WebrpcError");
    error->message = smoke_strdup(message ? message : "request failed");
    error->cause = cause ? smoke_strdup(cause) : NULL;
}

static int smoke_buffer_grow(smoke_buffer *buf, size_t need) {
    if (!buf) return 0;
    if (buf->cap >= need) return 1;
    size_t new_cap = buf->cap ? buf->cap : 1024;
    while (new_cap < need) {
        if (new_cap > SIZE_MAX / 2) {
            new_cap = need;
            break;
        }
        new_cap *= 2;
    }
    char *next = (char *)realloc(buf->data, new_cap);
    if (!next) return 0;
    buf->data = next;
    buf->cap = new_cap;
    return 1;
}

static size_t smoke_write_cb(char *ptr, size_t size, size_t nmemb, void *userdata) {
    smoke_buffer *buf = (smoke_buffer *)userdata;
    size_t n;

    if (!buf) return 0;
    if (size != 0 && nmemb > SIZE_MAX / size) return 0;
    n = size * nmemb;
    if (buf->len > SIZE_MAX - n - 1) return 0;
    if (!smoke_buffer_grow(buf, buf->len + n + 1)) return 0;
    memcpy(buf->data + buf->len, ptr, n);
    buf->len += n;
    buf->data[buf->len] = '\0';
    return n;
}

static char *smoke_join_url(const char *base_url, const char *path) {
    if (!base_url) return NULL;
    if (!path) path = "";

    size_t base_len = strlen(base_url);
    size_t path_len = strlen(path);
    int base_has_slash = base_len > 0 && base_url[base_len - 1] == '/';
    int path_has_slash = path_len > 0 && path[0] == '/';
    size_t cap = base_len + path_len + 2;
    char *out = (char *)malloc(cap);
    if (!out) return NULL;

    if (base_len == 0) {
        snprintf(out, cap, "%s", path);
    } else if (path_len == 0) {
        snprintf(out, cap, "%s", base_url);
    } else if (base_has_slash && path_has_slash) {
        snprintf(out, cap, "%.*s%s", (int)(base_len - 1), base_url, path);
    } else if (!base_has_slash && !path_has_slash) {
        snprintf(out, cap, "%s/%s", base_url, path);
    } else {
        snprintf(out, cap, "%s%s", base_url, path);
    }
    return out;
}

static int smoke_append_header(struct curl_slist **headers, const char *header_value) {
    struct curl_slist *next;

    if (!headers || !header_value) return 0;
    next = curl_slist_append(*headers, header_value);
    if (!next) return 0;
    *headers = next;
    return 1;
}

static int smoke_header_name_equals(const char *header, const char *name) {
    size_t i = 0;

    if (!header || !name) return 0;

    while (header[i] != '\0' && header[i] != ':' && name[i] != '\0' && name[i] != ':') {
        unsigned char h = (unsigned char)header[i];
        unsigned char n = (unsigned char)name[i];
        if (h >= 'A' && h <= 'Z') h = (unsigned char)(h - 'A' + 'a');
        if (n >= 'A' && n <= 'Z') n = (unsigned char)(n - 'A' + 'a');
        if (h != n) return 0;
        i++;
    }

    while (header[i] == ' ' || header[i] == '\t') {
        i++;
    }

    while (name[i] == ' ' || name[i] == '\t') {
        i++;
    }

    return (name[i] == '\0' || name[i] == ':') && (header[i] == '\0' || header[i] == ':');
}

static int smoke_prepared_request_has_header(const smoke_prepared_request *request, const char *name) {
    if (!request || !name || !request->headers) return 0;

    for (size_t i = 0; i < request->headers_count; ++i) {
        if (request->headers[i] && smoke_header_name_equals(request->headers[i], name)) {
            return 1;
        }
    }

    return 0;
}

static int smoke_prepared_request_overrides_header(const smoke_prepared_request *request, const char *header_line) {
    if (!request || !header_line) return 0;

    if (smoke_header_name_equals(header_line, "Content-Type")) {
        if ((request->content_type && request->content_type[0] != '\0') ||
            smoke_prepared_request_has_header(request, "Content-Type")) {
            return 1;
        }
    }

    if (!request->headers) return 0;
    for (size_t i = 0; i < request->headers_count; ++i) {
        if (request->headers[i] &&
            smoke_header_name_equals(request->headers[i], header_line)) {
            return 1;
        }
    }

    return 0;
}

static int smoke_build_request_headers(
    const smoke_prepared_request *request,
    const char *bearer_token,
    const struct curl_slist *default_headers,
    struct curl_slist **out_headers,
    smoke_error *error
) {
    int has_content_type = 0;
    int has_authorization = 0;
    struct curl_slist *headers = NULL;

    if (!request || !out_headers) {
        smoke_set_error(error, 0, 0, "ClientError", "request headers must be built from a valid request", NULL);
        return -1;
    }

    for (const struct curl_slist *it = default_headers; it; it = it->next) {
        if ((bearer_token && bearer_token[0] != '\0' && smoke_header_name_equals(it->data, "Authorization")) ||
            smoke_prepared_request_overrides_header(request, it->data)) {
            continue;
        }
        if (!smoke_append_header(&headers, it->data)) {
            smoke_set_error(error, 0, 0, "TransportError", "failed to copy request headers", NULL);
            curl_slist_free_all(headers);
            return -1;
        }
        if (smoke_header_name_equals(it->data, "Content-Type")) {
            has_content_type = 1;
        }
        if (smoke_header_name_equals(it->data, "Authorization")) {
            has_authorization = 1;
        }
    }

    if (request->content_type && request->content_type[0] != '\0') {
        size_t need = strlen("Content-Type: ") + strlen(request->content_type) + 1;
        char *content_type_header = (char *)malloc(need);
        if (!content_type_header) {
            smoke_set_error(error, 0, 0, "TransportError", "failed to allocate content-type header", NULL);
            curl_slist_free_all(headers);
            return -1;
        }
        snprintf(content_type_header, need, "Content-Type: %s", request->content_type);
        if (!smoke_append_header(&headers, content_type_header)) {
            smoke_set_error(error, 0, 0, "TransportError", "failed to append content-type header", NULL);
            free(content_type_header);
            curl_slist_free_all(headers);
            return -1;
        }
        free(content_type_header);
        has_content_type = 1;
    }

    for (size_t i = 0; i < request->headers_count; ++i) {
        if (!request->headers || !request->headers[i]) {
            smoke_set_error(error, 0, 0, "TransportError", "request headers are invalid", NULL);
            curl_slist_free_all(headers);
            return -1;
        }
        if (!smoke_append_header(&headers, request->headers[i])) {
            smoke_set_error(error, 0, 0, "TransportError", "failed to append request header", NULL);
            curl_slist_free_all(headers);
            return -1;
        }
        if (smoke_header_name_equals(request->headers[i], "Content-Type")) {
            has_content_type = 1;
        }
        if (smoke_header_name_equals(request->headers[i], "Authorization")) {
            has_authorization = 1;
        }
    }

    if (!has_content_type && !smoke_append_header(&headers, "Content-Type: application/json")) {
        smoke_set_error(error, 0, 0, "TransportError", "failed to allocate request headers", NULL);
        curl_slist_free_all(headers);
        return -1;
    }
    if (bearer_token && bearer_token[0] != '\0' && !has_authorization) {
        size_t need = strlen("Authorization: Bearer ") + strlen(bearer_token) + 1;
        char *auth_header = (char *)malloc(need);
        if (!auth_header) {
            smoke_set_error(error, 0, 0, "TransportError", "failed to allocate auth header", NULL);
            curl_slist_free_all(headers);
            return -1;
        }
        snprintf(auth_header, need, "Authorization: Bearer %s", bearer_token);
        if (!smoke_append_header(&headers, auth_header)) {
            smoke_set_error(error, 0, 0, "TransportError", "failed to append auth header", NULL);
            free(auth_header);
            curl_slist_free_all(headers);
            return -1;
        }
        free(auth_header);
    }

    *out_headers = headers;
    return 0;
}

int smoke_runtime_init(smoke_error *error) {
    CURLcode init_rc = curl_global_init(CURL_GLOBAL_DEFAULT);
    if (init_rc != CURLE_OK) {
        smoke_set_error(error, 0, 0, "TransportError", "curl_global_init failed", curl_easy_strerror(init_rc));
        return -1;
    }
    return 0;
}

void smoke_runtime_cleanup(void) {
    curl_global_cleanup();
}

static int smoke_http_send_request(
    const char *base_url,
    const smoke_prepared_request *request,
    const char *bearer_token,
    const struct curl_slist *default_headers,
    long timeout_ms,
    smoke_http_response *response,
    smoke_error *error
) {
    const char *http_method;
    char *url = NULL;
    CURL *curl = NULL;
    struct curl_slist *headers = NULL;
    smoke_buffer buf;
    smoke_http_response result;
    int rc = -1;
    int send_body = 1;

    if (!request || !response) {
        smoke_set_error(error, 0, 0, "ClientError", "request and response must be non-NULL", NULL);
        return -1;
    }
    smoke_http_response_init(&result);
    memset(&buf, 0, sizeof(buf));

    curl = curl_easy_init();
    if (!curl) {
        smoke_set_error(error, 0, 0, "TransportError", "curl_easy_init failed", NULL);
        return -1;
    }

    url = smoke_join_url(base_url, request->path ? request->path : "");
    if (!url) {
        smoke_set_error(error, 0, 0, "TransportError", "failed to build URL", NULL);
        curl_easy_cleanup(curl);
        return -1;
    }

    http_method = request->http_method && request->http_method[0] != '\0' ? request->http_method : "POST";
    if (strcmp(http_method, "HEAD") == 0) {
        send_body = 0;
    }

    if (smoke_build_request_headers(request, bearer_token, default_headers, &headers, error) != 0) {
        goto cleanup;
    }

    curl_easy_setopt(curl, CURLOPT_URL, url);
    curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
    curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, http_method);
    if (send_body) {
        curl_easy_setopt(curl, CURLOPT_POSTFIELDS, request->body ? request->body : "");
        curl_easy_setopt(curl, CURLOPT_POSTFIELDSIZE, (long)(request->body ? request->body_len : 0));
    } else if (strcmp(http_method, "HEAD") == 0) {
        curl_easy_setopt(curl, CURLOPT_NOBODY, 1L);
    }
    curl_easy_setopt(curl, CURLOPT_TIMEOUT_MS, timeout_ms > 0 ? timeout_ms : 10000L);
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, smoke_write_cb);
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, &buf);

    {
        CURLcode perform_rc = curl_easy_perform(curl);
        if (perform_rc != CURLE_OK) {
            smoke_set_error(error, 0, 0, "TransportError", "HTTP request failed", curl_easy_strerror(perform_rc));
            goto cleanup;
        }
    }

    curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &result.status_code);
    result.body = buf.data ? buf.data : smoke_strdup("");
    result.body_len = buf.len;
    buf.data = NULL;
    *response = result;
    memset(&result, 0, sizeof(result));
    rc = 0;

cleanup:
    free(buf.data);
    curl_slist_free_all(headers);
    free(url);
    curl_easy_cleanup(curl);
    if (rc != 0) {
        smoke_http_response_free(&result);
    }
    return rc;
}

static void smoke_parse_rpc_error(const char *body, long http_status, smoke_error *error) {
    cJSON *error_name = NULL;
    cJSON *error_code = NULL;
    cJSON *error_msg = NULL;
    cJSON *error_cause = NULL;
    cJSON *error_status = NULL;
    int64_t parsed_code = 0;
    int64_t parsed_status = (int64_t)http_status;

    if (!body || body[0] == '\0') {
        smoke_set_error(error, 0, (int)http_status, "WebrpcRequestFailed", "request failed", NULL);
        return;
    }

    cJSON *root = smoke_cjson_parse(body);
    if (!root || !cJSON_IsObject(root)) {
        if (root) cJSON_Delete(root);
        smoke_set_error(error, 0, (int)http_status, "WebrpcRequestFailed", "request failed", body);
        return;
    }

    error_name = cJSON_GetObjectItemCaseSensitive(root, "error");
    error_code = cJSON_GetObjectItemCaseSensitive(root, "code");
    error_msg = cJSON_GetObjectItemCaseSensitive(root, "msg");
    error_cause = cJSON_GetObjectItemCaseSensitive(root, "cause");
    error_status = cJSON_GetObjectItemCaseSensitive(root, "status");
    if (error_code && !cJSON_IsNull(error_code)) {
        (void)smoke_cjson_get_int64_exact(error_code, &parsed_code);
    }
    if (error_status && !cJSON_IsNull(error_status)) {
        (void)smoke_cjson_get_int64_exact(error_status, &parsed_status);
    }

    smoke_set_error(
        error,
        (int)parsed_code,
        (int)parsed_status,
        cJSON_IsString(error_name) && cJSON_GetStringValue(error_name) ? cJSON_GetStringValue(error_name) : "WebrpcRequestFailed",
        cJSON_IsString(error_msg) && cJSON_GetStringValue(error_msg) ? cJSON_GetStringValue(error_msg) : "request failed",
        cJSON_IsString(error_cause) ? cJSON_GetStringValue(error_cause) : NULL
    );
    cJSON_Delete(root);
}
static SMOKE_JSON_UNUSED cJSON *smoke_profile_to_json(const smoke_profile *value);
static SMOKE_JSON_UNUSED int smoke_profile_from_json(const cJSON *json, smoke_profile *out, smoke_error *error);


static SMOKE_JSON_UNUSED cJSON *smoke_profile_to_json(const smoke_profile *value) {
    if (!value) return NULL;
    cJSON *root = cJSON_CreateObject();
    if (!root) return NULL;
    {
            cJSON *field_json = NULL;

    field_json = value->id.digits ? cJSON_CreateString(value->id.digits) : cJSON_CreateNull();
    if (!field_json) goto fail;
            if (!cJSON_AddItemToObject(root, "id", field_json)) {
                cJSON_Delete(field_json);
                goto fail;
            }
    }
    {
            cJSON *field_json = NULL;

    field_json = value->name ? cJSON_CreateString(value->name) : cJSON_CreateNull();
    if (!field_json) goto fail;
            if (!cJSON_AddItemToObject(root, "name", field_json)) {
                cJSON_Delete(field_json);
                goto fail;
            }
    }
    {
            cJSON *field_json = NULL;

    field_json = cJSON_CreateString(smoke_role_to_string(value->role));
    if (!field_json) goto fail;
            if (!cJSON_AddItemToObject(root, "role", field_json)) {
                cJSON_Delete(field_json);
                goto fail;
            }
    }
    {
        if (value->has_tags) {
            cJSON *field_json = NULL;
{
        cJSON *array_json = cJSON_CreateArray();
        if (!array_json) goto fail;
        for (size_t list_idx_0 = 0; list_idx_0 < value->tags.count; ++list_idx_0) {
            cJSON *list_entry_json_0 = NULL;

    list_entry_json_0 = value->tags.items[list_idx_0] ? cJSON_CreateString(value->tags.items[list_idx_0]) : cJSON_CreateNull();
    if (!list_entry_json_0) goto fail;
            if (!cJSON_AddItemToArray(array_json, list_entry_json_0)) {
                cJSON_Delete(list_entry_json_0);
                cJSON_Delete(array_json);
                goto fail;
            }
        }
        field_json = array_json;
    }
            if (!cJSON_AddItemToObject(root, "tags", field_json)) {
                cJSON_Delete(field_json);
                goto fail;
            }
        }
    }
    {
        if (value->has_meta) {
            cJSON *field_json = NULL;

    {
        cJSON *object_json = cJSON_CreateObject();
        if (!object_json) goto fail;

        for (size_t map_idx_0 = 0; map_idx_0 < value->meta.count; ++map_idx_0) {
            const char *map_key_0 = value->meta.keys[map_idx_0];
            cJSON *map_value_json_0 = NULL;

    map_value_json_0 = value->meta.values[map_idx_0] ? cJSON_CreateString(value->meta.values[map_idx_0]) : cJSON_CreateNull();
    if (!map_value_json_0) goto fail;
            if (!map_key_0) {
                cJSON_Delete(map_value_json_0);
                cJSON_Delete(object_json);
                goto fail;
            }
            if (!cJSON_AddItemToObject(object_json, map_key_0, map_value_json_0)) {
                cJSON_Delete(map_value_json_0);
                cJSON_Delete(object_json);
                goto fail;
            }
        }
        field_json = object_json;
    }
            if (!cJSON_AddItemToObject(root, "meta", field_json)) {
                cJSON_Delete(field_json);
                goto fail;
            }
        }
    }
    return root;
fail:
    cJSON_Delete(root);
    return NULL;
}
static SMOKE_JSON_UNUSED int smoke_profile_from_json(const cJSON *json, smoke_profile *out, smoke_error *error) {
    if (!out) {
        smoke_set_error(error, 0, 0, "DecodeError", "output pointer is NULL", NULL);
        return -1;
    }
    if (!json || cJSON_IsNull(json)) return 0;
    if (!cJSON_IsObject(json)) {
        smoke_set_error(error, 0, 0, "DecodeError", "expected JSON object", NULL);
        return -1;
    }
    {
        cJSON *field_json = cJSON_GetObjectItemCaseSensitive(json, "id");
        int field_present = field_json != NULL;
        if (!field_present || cJSON_IsNull(field_json)) {
            smoke_set_error(error, 0, 0, "DecodeError", "missing required field id", NULL);
            goto fail;
        }

    if (!cJSON_IsString(field_json) || !cJSON_GetStringValue(field_json) || smoke_bigint_set_string(&out->id, cJSON_GetStringValue(field_json)) != 0) {
        smoke_set_error(error, 0, 0, "DecodeError", "expected bigint string", NULL);
        goto fail;
    }
    }
    {
        cJSON *field_json = cJSON_GetObjectItemCaseSensitive(json, "name");
        int field_present = field_json != NULL;
        if (!field_present || cJSON_IsNull(field_json)) {
            smoke_set_error(error, 0, 0, "DecodeError", "missing required field name", NULL);
            goto fail;
        }

    if (!cJSON_IsString(field_json) || !cJSON_GetStringValue(field_json)) {
        smoke_set_error(error, 0, 0, "DecodeError", "expected string", NULL);
        goto fail;
    }
    out->name = smoke_strdup(cJSON_GetStringValue(field_json));
    if (!out->name) {
        smoke_set_error(error, 0, 0, "DecodeError", "out of memory decoding string", NULL);
        goto fail;
    }
    }
    {
        cJSON *field_json = cJSON_GetObjectItemCaseSensitive(json, "role");
        int field_present = field_json != NULL;
        if (!field_present || cJSON_IsNull(field_json)) {
            smoke_set_error(error, 0, 0, "DecodeError", "missing required field role", NULL);
            goto fail;
        }

    if (!cJSON_IsString(field_json) || !cJSON_GetStringValue(field_json) || smoke_role_from_string(cJSON_GetStringValue(field_json), &out->role) != 0) {
        smoke_set_error(error, 0, 0, "DecodeError", "expected enum string", NULL);
        goto fail;
    }
    }
    {
        cJSON *field_json = cJSON_GetObjectItemCaseSensitive(json, "tags");
        int field_present = field_json != NULL;
        if (field_present) {
            out->has_tags = true;
            if (!cJSON_IsNull(field_json)) {
if (!cJSON_IsArray(field_json)) {
        smoke_set_error(error, 0, 0, "DecodeError", "expected JSON array", NULL);
        goto fail;
    }
    {
        size_t count = (size_t)cJSON_GetArraySize(field_json);
        out->tags.items = count ? calloc(count, sizeof(*out->tags.items)) : NULL;
        if (count && !out->tags.items) {
            smoke_set_error(error, 0, 0, "DecodeError", "out of memory decoding array", NULL);
            goto fail;
        }
        out->tags.count = count;
        for (size_t list_idx_0 = 0; list_idx_0 < count; ++list_idx_0) {
            cJSON *list_entry_0 = cJSON_GetArrayItem(field_json, (int)list_idx_0);

    if (!cJSON_IsString(list_entry_0) || !cJSON_GetStringValue(list_entry_0)) {
        smoke_set_error(error, 0, 0, "DecodeError", "expected string", NULL);
        goto fail;
    }
    out->tags.items[list_idx_0] = smoke_strdup(cJSON_GetStringValue(list_entry_0));
    if (!out->tags.items[list_idx_0]) {
        smoke_set_error(error, 0, 0, "DecodeError", "out of memory decoding string", NULL);
        goto fail;
    }
        }
    }
            }
        }
    }
    {
        cJSON *field_json = cJSON_GetObjectItemCaseSensitive(json, "meta");
        int field_present = field_json != NULL;
        if (field_present) {
            out->has_meta = true;
            if (!cJSON_IsNull(field_json)) {

    if (!cJSON_IsObject(field_json)) {
        smoke_set_error(error, 0, 0, "DecodeError", "expected JSON object", NULL);
        goto fail;
    }

    {
        size_t count = (size_t)cJSON_GetArraySize(field_json);
        out->meta.keys = count ? calloc(count, sizeof(*out->meta.keys)) : NULL;
        out->meta.values = count ? calloc(count, sizeof(*out->meta.values)) : NULL;
        if (count && (!out->meta.keys || !out->meta.values)) {
            smoke_set_error(error, 0, 0, "DecodeError", "out of memory decoding map", NULL);
            goto fail;
        }
        out->meta.count = count;
        size_t map_idx_0 = 0;
        cJSON *map_entry_0 = NULL;
        cJSON_ArrayForEach(map_entry_0, field_json) {
            const char *entry_key = map_entry_0 ? map_entry_0->string : NULL;
            if (!entry_key) {
                smoke_set_error(error, 0, 0, "DecodeError", "missing map key", NULL);
                goto fail;
            }

    out->meta.keys[map_idx_0] = smoke_strdup(entry_key);
    if (!out->meta.keys[map_idx_0]) {
        smoke_set_error(error, 0, 0, "DecodeError", "out of memory decoding map key", NULL);
        goto fail;
    }

    if (!cJSON_IsString(map_entry_0) || !cJSON_GetStringValue(map_entry_0)) {
        smoke_set_error(error, 0, 0, "DecodeError", "expected string", NULL);
        goto fail;
    }
    out->meta.values[map_idx_0] = smoke_strdup(cJSON_GetStringValue(map_entry_0));
    if (!out->meta.values[map_idx_0]) {
        smoke_set_error(error, 0, 0, "DecodeError", "out of memory decoding string", NULL);
        goto fail;
    }
            map_idx_0++;
        }
    }
            }
        }
    }
    return 0;
fail:
    smoke_profile_free(out);
    return -1;
}
static int smoke_prepare_json_request(
    cJSON *request_json,
    const char *path,
    smoke_prepared_request *prepared_request,
    smoke_error *error
) {
    int rc = -1;
    char *request_body = NULL;
    smoke_prepared_request prepared;
    smoke_prepared_request_init(&prepared);

    if (!request_json || !path || !prepared_request) {
        smoke_set_error(error, 0, 0, "ClientError", "request_json, path and prepared_request must be non-NULL", NULL);
        goto fail;
    }

    request_body = smoke_cjson_print_dup(request_json);
    if (!request_body) {
        smoke_set_error(error, 0, 0, "EncodeError", "failed to print request JSON", NULL);
        goto fail;
    }

    prepared.http_method = smoke_strdup("POST");
    prepared.path = smoke_strdup(path);
    prepared.content_type = smoke_strdup("application/json");
    if (!prepared.http_method || !prepared.path || !prepared.content_type) {
        smoke_set_error(error, 0, 0, "EncodeError", "failed to allocate prepared request metadata", NULL);
        goto fail;
    }

    prepared.body = request_body;
    prepared.body_len = strlen(request_body);
    request_body = NULL;

    *prepared_request = prepared;
    memset(&prepared, 0, sizeof(prepared));
    rc = 0;

fail:
    smoke_prepared_request_free(&prepared);
    free(request_body);
    return rc;
}

static int smoke_parse_json_response(
    const smoke_http_response *http_response,
    cJSON **response_json,
    smoke_error *error
) {
    if (!http_response || !response_json) {
        smoke_set_error(error, 0, 0, "ClientError", "http_response and response_json must be non-NULL", NULL);
        return -1;
    }
    if (http_response->status_code < 200 || http_response->status_code >= 300) {
        smoke_parse_rpc_error(http_response->body, http_response->status_code, error);
        return -1;
    }

    *response_json = smoke_cjson_parse(http_response->body ? http_response->body : "{}");
    if (!*response_json) {
        smoke_set_error(error, 0, (int)http_response->status_code, "DecodeError", "failed to parse response JSON", http_response->body);
        return -1;
    }

    return 0;
}
static cJSON *smoke_smoke_echo_request_to_json(const smoke_smoke_echo_request *value) {
    if (!value) return cJSON_CreateObject();
    cJSON *root = cJSON_CreateObject();
    if (!root) return NULL;
    {
            cJSON *field_json = NULL;

    if (value->profile) {
        field_json = smoke_profile_to_json(value->profile);
    } else {
        field_json = cJSON_CreateNull();
    }
    if (!field_json) goto fail;
            if (!cJSON_AddItemToObject(root, "profile", field_json)) {
                cJSON_Delete(field_json);
                goto fail;
            }
    }
    return root;
fail:
    cJSON_Delete(root);
    return NULL;
}

static int smoke_smoke_echo_response_from_json(const cJSON *json, smoke_smoke_echo_response *out, smoke_error *error) {
    if (!out) {
        smoke_set_error(error, 0, 0, "DecodeError", "output pointer is NULL", NULL);
        return -1;
    }
    if (!json || !cJSON_IsObject(json)) {
        smoke_set_error(error, 0, 0, "DecodeError", "expected JSON object", NULL);
        return -1;
    }
    {
        cJSON *field_json = cJSON_GetObjectItemCaseSensitive(json, "profile");
        int field_present = field_json != NULL;
        if (!field_present || cJSON_IsNull(field_json)) {
            smoke_set_error(error, 0, 0, "DecodeError", "missing required field profile", NULL);
            goto fail;
        }

    if (!cJSON_IsObject(field_json)) {
        smoke_set_error(error, 0, 0, "DecodeError", "expected JSON object", NULL);
        goto fail;
    }
    out->profile = (smoke_profile *)calloc(1, sizeof(*out->profile));
    if (!out->profile) {
        smoke_set_error(error, 0, 0, "DecodeError", "out of memory decoding object", NULL);
        goto fail;
    }
    if (smoke_profile_from_json(field_json, out->profile, error) != 0) {
        goto fail;
    }
    }
    return 0;
fail:
    smoke_smoke_echo_response_free(out);
    return -1;
}

int smoke_smoke_echo_prepare_request(
    const smoke_smoke_echo_request *request,
    smoke_prepared_request *prepared_request,
    smoke_error *error
) {
    int rc = -1;
    cJSON *request_json = NULL;

    if (!request || !prepared_request) {
        smoke_set_error(error, 0, 0, "ClientError", "request and prepared_request must be non-NULL", NULL);
        goto fail;
    }

    request_json = smoke_smoke_echo_request_to_json(request);
    if (!request_json) {
        smoke_set_error(error, 0, 0, "EncodeError", "failed to encode request JSON", NULL);
        goto fail;
    }

    rc = smoke_prepare_json_request(request_json, "/rpc/Smoke/Echo", prepared_request, error);

fail:
    cJSON_Delete(request_json);
    return rc;
}

int smoke_smoke_echo_parse_response(
    const smoke_http_response *http_response,
    smoke_smoke_echo_response *response,
    smoke_error *error
) {
    int rc = -1;
    cJSON *response_json = NULL;
    smoke_smoke_echo_response parsed_response;
    smoke_smoke_echo_response_init(&parsed_response);

    if (!http_response || !response) {
        smoke_set_error(error, 0, 0, "ClientError", "http_response and response must be non-NULL", NULL);
        goto fail;
    }
    if (smoke_parse_json_response(http_response, &response_json, error) != 0) {
        goto fail;
    }
    if (smoke_smoke_echo_response_from_json(response_json, &parsed_response, error) != 0) {
        goto fail;
    }

    *response = parsed_response;
    memset(&parsed_response, 0, sizeof(parsed_response));
    rc = 0;

fail:
    smoke_smoke_echo_response_free(&parsed_response);
    cJSON_Delete(response_json);
    return rc;
}

struct smoke_smoke_client {
    char *base_url;
    char *bearer_token;
    struct curl_slist *default_headers;
    long timeout_ms;
};

static void smoke_smoke_client_free_config_parts(char **bearer_token, struct curl_slist **default_headers) {
    if (bearer_token && *bearer_token) {
        free(*bearer_token);
        *bearer_token = NULL;
    }
    if (default_headers && *default_headers) {
        curl_slist_free_all(*default_headers);
        *default_headers = NULL;
    }
}

static void smoke_smoke_client_reset_config(smoke_smoke_client *client) {
    if (!client) return;
    smoke_smoke_client_free_config_parts(&client->bearer_token, &client->default_headers);
    client->timeout_ms = 10000L;
}

static int smoke_smoke_client_build_config(
    const smoke_client_options *options,
    char **bearer_token,
    struct curl_slist **default_headers,
    long *timeout_ms
) {
    if (!bearer_token || !default_headers || !timeout_ms) return 0;
    *bearer_token = NULL;
    *default_headers = NULL;
    *timeout_ms = 10000L;
    if (!options) return 1;

    if (options->timeout_ms > 0) {
        *timeout_ms = options->timeout_ms;
    }

    if (options->bearer_token) {
        *bearer_token = smoke_strdup(options->bearer_token);
        if (!*bearer_token) goto fail;
    }

    if (options->headers_count > 0) {
        if (!options->headers) goto fail;
        for (size_t i = 0; i < options->headers_count; ++i) {
            if (!options->headers[i]) goto fail;
            struct curl_slist *next = curl_slist_append(*default_headers, options->headers[i]);
            if (!next) goto fail;
            *default_headers = next;
        }
    }

    return 1;

fail:
    smoke_smoke_client_free_config_parts(bearer_token, default_headers);
    *timeout_ms = 10000L;
    return 0;
}

int smoke_smoke_client_configure(smoke_smoke_client *client, const smoke_client_options *options) {
    char *next_bearer_token = NULL;
    struct curl_slist *next_default_headers = NULL;
    long next_timeout_ms = 10000L;

    if (!client) return 0;
    if (!smoke_smoke_client_build_config(options, &next_bearer_token, &next_default_headers, &next_timeout_ms)) {
        return 0;
    }

    smoke_smoke_client_reset_config(client);
    client->bearer_token = next_bearer_token;
    client->default_headers = next_default_headers;
    client->timeout_ms = next_timeout_ms;
    return 1;
}

smoke_smoke_client *smoke_smoke_client_create(const char *base_url, const smoke_client_options *options) {
    smoke_smoke_client *client =
        (smoke_smoke_client *)calloc(1, sizeof(*client));
    if (!client) return NULL;
    client->base_url = smoke_strdup(base_url ? base_url : "");
    if (!client->base_url) {
        free(client);
        return NULL;
    }
    smoke_smoke_client_reset_config(client);
    if (!smoke_smoke_client_configure(client, options)) {
        free(client->base_url);
        client->base_url = NULL;
        smoke_smoke_client_reset_config(client);
        free(client);
        return NULL;
    }
    return client;
}

void smoke_smoke_client_destroy(smoke_smoke_client *client) {
    if (!client) return;
    free(client->base_url);
    client->base_url = NULL;
    smoke_smoke_client_reset_config(client);
    free(client);
}

int smoke_smoke_client_send_prepared_request(
    smoke_smoke_client *client,
    const smoke_prepared_request *request,
    smoke_http_response *response,
    smoke_error *error
) {
    if (!client || !request || !response) {
        smoke_set_error(error, 0, 0, "ClientError", "client, request, and response must be non-NULL", NULL);
        return -1;
    }

    return smoke_http_send_request(
        client->base_url,
        request,
        client->bearer_token,
        client->default_headers,
        client->timeout_ms,
        response,
        error
    );
}
int smoke_smoke_echo(
    smoke_smoke_client *client,
    const smoke_smoke_echo_request *request,
    smoke_smoke_echo_response *response,
    smoke_error *error
) {
    int rc = -1;
    smoke_prepared_request prepared_request;
    smoke_http_response http_response;
    smoke_prepared_request_init(&prepared_request);
    smoke_http_response_init(&http_response);

    if (!client || !request || !response) {
        smoke_set_error(error, 0, 0, "ClientError", "client, request, and response must be non-NULL", NULL);
        goto fail;
    }

    if (smoke_smoke_echo_prepare_request(request, &prepared_request, error) != 0) {
        goto fail;
    }
    if (smoke_smoke_client_send_prepared_request(client, &prepared_request, &http_response, error) != 0) {
        goto fail;
    }
    if (smoke_smoke_echo_parse_response(&http_response, response, error) != 0) {
        goto fail;
    }
    rc = 0;

fail:
    smoke_prepared_request_free(&prepared_request);
    smoke_http_response_free(&http_response);
    return rc;
}