#ifndef SMOKE_SMOKE_HEADER_H
#define SMOKE_SMOKE_HEADER_H

// smoke v1.0.0 6dc82371b24d044c3b3e2bd4cf5d92af46788fff
// --
// Code generated by webrpc-gen@v0.37.1 with .. generator. DO NOT EDIT.
//
// webrpc-gen -schema=smoke/example.ridl -target=.. -emit=header -out=smoke/example.gen.h

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    char *digits;
} smoke_bigint;

typedef struct {
    char *value;
} smoke_timestamp;

typedef struct {
    int code;
    int http_status;
    char *name;
    char *message;
    char *cause;
} smoke_error;

typedef struct {
    char *http_method;
    char *path;
    char *body;
    size_t body_len;
    char *content_type;
    char **headers;
    size_t headers_count;
} smoke_prepared_request;

typedef struct {
    long status_code;
    char *body;
    size_t body_len;
} smoke_http_response;

typedef struct {
    const char *bearer_token;
    const char * const *headers;
    size_t headers_count;
    long timeout_ms;
} smoke_client_options;

static inline char *smoke_strdup(const char *value) {
    if (!value) return NULL;
    size_t n = strlen(value) + 1;
    char *copy = (char *)malloc(n);
    if (!copy) return NULL;
    memcpy(copy, value, n);
    return copy;
}

static inline void smoke_bigint_init(smoke_bigint *value) {
    if (!value) return;
    value->digits = NULL;
}

static inline void smoke_bigint_free(smoke_bigint *value) {
    if (!value) return;
    free(value->digits);
    value->digits = NULL;
}

static inline int smoke_bigint_set_string(smoke_bigint *value, const char *digits) {
    if (!value || !digits || digits[0] == '\0') return -1;

    size_t start = 0;
    bool negative = false;
    if (digits[0] == '+') return -1;
    if (digits[0] == '-') {
        negative = true;
        start = 1;
    }
    if (digits[start] == '\0') return -1;

    for (size_t i = start; digits[i] != '\0'; ++i) {
        if (digits[i] < '0' || digits[i] > '9') return -1;
    }

    while (digits[start] == '0' && digits[start + 1] != '\0') {
        start++;
    }
    if (digits[start] == '0') negative = false;

    size_t len = strlen(digits + start);
    size_t total = len + (negative ? 2 : 1);
    char *normalized = (char *)malloc(total);
    if (!normalized) return -1;

    if (negative) {
        normalized[0] = '-';
        memcpy(normalized + 1, digits + start, len + 1);
    } else {
        memcpy(normalized, digits + start, len + 1);
    }

    free(value->digits);
    value->digits = normalized;
    return 0;
}

static inline void smoke_timestamp_init(smoke_timestamp *value) {
    if (!value) return;
    value->value = NULL;
}

static inline void smoke_timestamp_free(smoke_timestamp *value) {
    if (!value) return;
    free(value->value);
    value->value = NULL;
}

static inline int smoke_timestamp_set_string(smoke_timestamp *value, const char *timestamp) {
    if (!value) return -1;
    char *copy = smoke_strdup(timestamp);
    if (timestamp && !copy) return -1;
    free(value->value);
    value->value = copy;
    return 0;
}

static inline void smoke_error_init(smoke_error *error) {
    if (!error) return;
    memset(error, 0, sizeof(*error));
}

static inline void smoke_error_free(smoke_error *error) {
    if (!error) return;
    free(error->name);
    free(error->message);
    free(error->cause);
    memset(error, 0, sizeof(*error));
}

static inline void smoke_prepared_request_init(smoke_prepared_request *request) {
    if (!request) return;
    memset(request, 0, sizeof(*request));
}

static inline void smoke_prepared_request_free(smoke_prepared_request *request) {
    if (!request) return;
    free(request->http_method);
    free(request->path);
    free(request->body);
    free(request->content_type);
    if (request->headers) {
        for (size_t i = 0; i < request->headers_count; ++i) {
            free(request->headers[i]);
        }
        free(request->headers);
    }
    memset(request, 0, sizeof(*request));
}

static inline int smoke_prepared_request_add_header(smoke_prepared_request *request, const char *header) {
    char **next_headers;
    char *copy;

    if (!request || !header) return -1;

    next_headers = (char **)realloc(request->headers, sizeof(*next_headers) * (request->headers_count + 1));
    if (!next_headers) return -1;
    request->headers = next_headers;

    copy = smoke_strdup(header);
    if (!copy) {
        return -1;
    }

    request->headers[request->headers_count] = copy;
    request->headers_count += 1;
    return 0;
}

static inline void smoke_http_response_init(smoke_http_response *response) {
    if (!response) return;
    memset(response, 0, sizeof(*response));
}

static inline void smoke_http_response_free(smoke_http_response *response) {
    if (!response) return;
    free(response->body);
    response->body = NULL;
    response->body_len = 0;
    response->status_code = 0;
}

static inline void smoke_client_options_init(smoke_client_options *options) {
    if (!options) return;
    memset(options, 0, sizeof(*options));
    options->timeout_ms = 10000L;
}


typedef struct smoke_profile smoke_profile;
static inline void smoke_profile_init(smoke_profile *value);
static inline void smoke_profile_free(smoke_profile *value);
typedef enum smoke_role {
    SMOKE_ROLE_UNKNOWN = 0,
    SMOKE_ROLE_USER,
    SMOKE_ROLE_ADMIN,
} smoke_role;

static inline const char *smoke_role_to_string(smoke_role value) {
    switch (value) {
        case SMOKE_ROLE_UNKNOWN: return "UNKNOWN";
        case SMOKE_ROLE_USER: return "USER";
        case SMOKE_ROLE_ADMIN: return "ADMIN";
        default: return "UNKNOWN";
    }
}

static inline int smoke_role_from_string(const char *value, smoke_role *out) {
    if (!out || !value) return -1;
    if (strcmp(value, "USER") == 0) {
        *out = SMOKE_ROLE_USER;
        return 0;
    }
    if (strcmp(value, "ADMIN") == 0) {
        *out = SMOKE_ROLE_ADMIN;
        return 0;
    }
    *out = SMOKE_ROLE_UNKNOWN;
    return -1;
}
struct smoke_profile {
    smoke_bigint id;
    char * name;
    smoke_role role;
    bool has_tags;
    struct {
    char * *items;
    size_t count;
} tags;
    bool has_meta;
    struct {
    char * *keys;
    char * *values;
    size_t count;
} meta;
};

static inline void smoke_profile_init(smoke_profile *value) {
    if (!value) return;
    memset(value, 0, sizeof(*value));
}

static inline void smoke_profile_free(smoke_profile *value) {
    if (!value) return;

    smoke_bigint_free(&value->id);

    free(value->name);
    value->name = NULL;


    if (value->tags.items) {
        for (size_t free_list_idx_0 = 0; free_list_idx_0 < value->tags.count; ++free_list_idx_0) {

    free(value->tags.items[free_list_idx_0]);
    value->tags.items[free_list_idx_0] = NULL;
        }
        free(value->tags.items);
        value->tags.items = NULL;
        value->tags.count = 0;
    }

    if (value->meta.keys || value->meta.values) {
        for (size_t free_map_idx_0 = 0; free_map_idx_0 < value->meta.count; ++free_map_idx_0) {

    free(value->meta.keys[free_map_idx_0]);
    value->meta.keys[free_map_idx_0] = NULL;

    free(value->meta.values[free_map_idx_0]);
    value->meta.values[free_map_idx_0] = NULL;
        }
        free(value->meta.keys);
        free(value->meta.values);
        value->meta.keys = NULL;
        value->meta.values = NULL;
        value->meta.count = 0;
    }
    memset(value, 0, sizeof(*value));
}
typedef struct smoke_smoke_echo_request {
    smoke_profile * profile;
} smoke_smoke_echo_request;

static inline void smoke_smoke_echo_request_init(smoke_smoke_echo_request *value) {
    if (!value) return;
    memset(value, 0, sizeof(*value));
}

static inline void smoke_smoke_echo_request_free(smoke_smoke_echo_request *value) {
    if (!value) return;

    if (value->profile) {
        smoke_profile_free(value->profile);
        free(value->profile);
        value->profile = NULL;
    }
    memset(value, 0, sizeof(*value));
}

typedef struct smoke_smoke_echo_response {
    smoke_profile * profile;
} smoke_smoke_echo_response;

static inline void smoke_smoke_echo_response_init(smoke_smoke_echo_response *value) {
    if (!value) return;
    memset(value, 0, sizeof(*value));
}

static inline void smoke_smoke_echo_response_free(smoke_smoke_echo_response *value) {
    if (!value) return;

    if (value->profile) {
        smoke_profile_free(value->profile);
        free(value->profile);
        value->profile = NULL;
    }
    memset(value, 0, sizeof(*value));
}

typedef struct smoke_smoke_client smoke_smoke_client;

smoke_smoke_client *smoke_smoke_client_create(const char *base_url, const smoke_client_options *options);
void smoke_smoke_client_destroy(smoke_smoke_client *client);
int smoke_smoke_client_configure(smoke_smoke_client *client, const smoke_client_options *options);
int smoke_smoke_client_send_prepared_request(
    smoke_smoke_client *client,
    const smoke_prepared_request *request,
    smoke_http_response *response,
    smoke_error *error
);
int smoke_smoke_echo_prepare_request(
    const smoke_smoke_echo_request *request,
    smoke_prepared_request *prepared_request,
    smoke_error *error
);

int smoke_smoke_echo_parse_response(
    const smoke_http_response *http_response,
    smoke_smoke_echo_response *response,
    smoke_error *error
);

int smoke_smoke_echo(
    smoke_smoke_client *client,
    const smoke_smoke_echo_request *request,
    smoke_smoke_echo_response *response,
    smoke_error *error
);

#ifdef __cplusplus
} // extern "C"
#endif

#endif // SMOKE_SMOKE_HEADER_H